apiVersion: v1
kind: Service
metadata:
  labels:
    app: dayz
  name: dayz-admin
  namespace: dayz
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: status
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: dayz
  type: LoadBalancer