---
apiVersion: v1
kind: Secret
metadata:
  name: steamaccount
  namespace: dayz
  labels:
    app: dayz
type: Opaque
data:
  STEAMACCOUNT: BASE64 STEAMACCOUNT
  STEAMPASSWORD: BASE64 STEAMACCOUNT PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: dayz-rcon
  namespace: dayz
  labels:
    app: dayz
type: Opaque
stringData:
  RCON_PASSWORD: CHANGE_ME
